version = 1

[[analyzers]]
name = "ruby"
enabled = true

[[transformers]]
name = "rubocop"
enabled = true

[[transformers]]
name = "standardrb"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true