AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Metrics/BlockLength:
  Exclude:
    - 'database/schema.rb'

Style/OpenStructUse:
  Exclude:
    - 'config/environment.rb'

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: false